plugins {
    id 'com.android.application'
}

android {
    namespace 'com.example.lab3'
    compileSdk 35

    defaultConfig {
        applicationId 'com.example.lab3'
        minSdk 23
        targetSdk 35
        versionCode 1
        versionName '1.0'
    }

    buildTypes {
        release {
            minifyEnabled false
        }
    }
}

dependencies {
    implementation 'com.amazon.ion:ion-java:1.10.5'
}
